### ISSUE TITLE
Code has `...ops` bugs now

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fitToParent#2]
This new version has introduced bugs, for some reason there are a few `...ops` in here.

```
    const settings = {
        heightOffset: 0,
        widthOffset: 0,
        parentHeight: sizeParent.offsetHeight,
        parentWidth: sizeParent.offsetWidth,
        callback: null,
        ratio: null,
        upres: true,
        elHeight,
        elWidth,
        ...ops
    }
```

and:

```
            this.each(function(){
                fitToParent({ element: this, ...ops })
                return this
            })
```

**Comment by johndigital** [comment]
It's actually just es2016 syntax, you can [read about it here](https://rainsoft.io/how-three-dots-changed-javascript/). Basically just a shorthand way to merge objects.

It's not safe to use the [development file](https://github.com/funkhaus/fitToParent/blob/master/fitToParent.js) anymore, since it has to be pre-processed and will throw errors. Use the [production file](https://github.com/funkhaus/fitToParent/blob/master/fitToParent.min.js) instead and everything will work fine.

**Comment by drewbaker** [comment]
I tried that first, got errors, so ended up with this issue ticket. Sounds like they are different bugs though.

![screen shot 2017-08-10 at 1 43 45 pm](https://user-images.githubusercontent.com/475015/29191259-fad3369a-7dd1-11e7-8b4f-1c9dceb5349a.png)

**Comment by johndigital** [comment]
@drewbaker hmm, can you paste in an example of how you're calling it?

classList is [pretty well supported](http://caniuse.com/#search=classList), I can't imagine your browser would have problems with it.

**Comment by johndigital** [comment]
@drewbaker actually I bet it's happening when you're calling it when the jQuery selector doesn't return anything right? I think I need to account for that in the plugin.

**Comment by johndigital** [comment]
@drewbaker let me know if the newest commit works for you.

**Comment by johndigital** [comment]
@drewbaker give this a test and see if it works? Would love to get this issue closed.
